name: rick_and_morty_app
description: Rick and Morty Character Explorer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0

  # Dependency Injection
  get_it: ^7.6.0

  # Network
  dio: ^5.4.0
  json_annotation: ^4.8.1

  # Storage
  shared_preferences: ^2.2.2

  # UI
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.1.1+1

  # Utils
  go_router: ^10.0.0
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  logger: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/